# Nom du site
site_name: Bioinfo training

# Description facultative (utilisée dans les métadonnées et les moteurs de recherche)
site_description: ""

# URL de base (utile pour le déploiement sur GitHub Pages)
site_url: https://srh-bzd.github.io/bioinfo-training

# URL et nom du repo
repo_url: https://github.com/srh-bzd/bioinfo-training
repo_name: srh-bzd/bioinfo-training

edit_uri: edit/main/docs/

# Chemin du logo
# logo: images/logo.png

# Thème Material
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - header.autohide
  palette:
    - scheme: default
      primary: black 
      accent: blue 
      toggle:
        icon: material/lightbulb-night-outline
        name: Mode sombre
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Mode clair
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy
    - navigation.tabs
    - search.highlight

# Configuration des plugins
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

# Extensions Markdown
markdown_extensions:
  - tables          
  - toc             
  - codehilite     
  - pymdownx.extra  
  - pymdownx.snippets  

# Structure de la navigation
nav:
  - Accueil: index.md
  - Cours : 
    - Vue d'ensemble : lessons/lessons.md
    - RNAseq : lessons/rnaseq-lesson.md
  - Tutoriels : 
    - Vue d'ensemble : training/training.md
    - Analyses :
      - RNAseq : training/analysis/rnaseq-training.md
    - Développement :
      - MkDocs : training/dev/mkdocs.md
  - Connaissances : 
    - Vue d'ensemble : knowledge/knowledge.md
    - Bases de données : 
      - RefSeq : knowledge/databases/refseq.md
    - Références : 
      - Le transcriptome humain : knowledge/references/human-transcriptome.md
      - Le génome humain: knowledge/references/human-genome.md
      - Les annotations du génome humain : knowledge/references/human-annotations.md
    - Outils :
      - Inférence du strandedness : knowledge/tools/rnaseq-strandedness.md
      - Biais d'assemblage : knowledge/tools/assembly-bias.md
  - À propos: about.md

# Options d'exclusion
exclude:
  - README.md
  - "*.tmp"


